# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/home/cjl/.local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/cjl/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="strug"
ZSH_THEME="clean"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
alias pn="ps -ef|grep nginx|grep -v grep"
alias kn="killall -9 nginx"
alias dbwaf="mysql -usec_goconfigkeeper_goc_db_r -pJgyTNkG4UhIZep1 -Dgoconfigkeeper_db -h192.168.55.3"
alias stopgk="/home/cjl/gatekeeper/waf_judge/nginx-1.9.14/objs/nginx -p /home/cjl/gatekeeper/waf_judge/nginx-1.9.14/ -s stop"
alias dim="docker images"
alias dps="docker ps -a"
alias dlog="docker logs -f"
alias dritd="docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged -v ~/.ssh/:/root/.ssh/ -v /etc/localtime:/etc/localtime:ro -itd "
alias drit="docker run --privileged -v ~/.ssh/:/root/.ssh/ -v /etc/localtime:/etc/localtime:ro -it "
alias db="docker build" 

function timestamp() {
    echo `perl -e 'print time'`
}

alias ts=timestamp

function docker_exec_it_bash() {
	docker exec -it $1 bash
}

function docker_exec_it_command() {
	docker exec -it $@ 
}
alias deb=docker_exec_it_bash
alias de=docker_exec_it_command


alias zshrc="vim ~/.zshrc"

function docker_kill_all() {
	docker kill $(docker ps -qa)
	docker rm $(docker ps -qa)
	docker rmi $(docker images | grep "none" | awk '{print $3}')
}
alias dkillall=docker_kill_all

alias agent="cd /home/cjl/dfe/nginx/output"
alias gk="cd /home/cjl/gatekeeper/waf_judge/nginx-1.9.14"
alias c="clear"
alias empty="cat /dev/null >"

function chpwd() {
    emulate -L zsh
        ls -l
}
#export GOPROXY=https://goproxy.io
export EDITOR=vim
