export PATH=$HOME/bin:/usr/local/bin:/home/cjl/.local/bin:$PATH
export ZSH="/home/cjl/.oh-my-zsh"

ZSH_THEME="clean"
plugins=(git)

source $ZSH/oh-my-zsh.sh

alias pn="ps -ef|grep nginx|grep -v grep"
alias kn="killall -9 nginx"
alias dim="docker images"
alias dps="docker ps -a"
alias dlog="docker logs -f"
alias dritd="docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged -v ~/.ssh/:/root/.ssh/ -v /etc/localtime:/etc/localtime:ro -itd "
alias drit="docker run --privileged -v ~/.ssh/:/root/.ssh/ -v /etc/localtime:/etc/localtime:ro -it "
alias db="docker build" 

function timestamp() {
    echo `perl -e 'print time'`
}


function docker_exec_it_bash() {
	docker exec -it $1 bash
}

function docker_exec_it_command() {
	docker exec -it $@ 
}
alias deb=docker_exec_it_bash
alias de=docker_exec_it_command


alias zshrc="vim ~/.zshrc"

function docker_kill_all() {
	docker kill $(docker ps -qa)
	docker rm $(docker ps -qa)
	docker rmi $(docker images | grep "none" | awk '{print $3}')
}
alias dkillall=docker_kill_all

alias c="clear"
alias empty="cat /dev/null >"

function chpwd() {
    emulate -L zsh
        ls -l
}
#export GOPROXY=https://goproxy.io
function arbitrary_base_conversion () {
    if (( $# != 3 )); then
        echo "usage: ./arbitrary_base_conversion input_base output_base num (./x2y 10 2 5 will get 101)" >&2
        exit 22 
    fi
    echo "obase=$2;ibase=$1;$3" | bc
}
export EDITOR=vim
alias ts=timestamp
alias addr2line="addr2line -pfe"
alias empty="cat /dev/null >"
alias gdb="gdb -tui"
alias x2y=arbitrary_base_conversion
